# Exploring first and second derivatives with Julia


To get started, we load the `MTH229` package:


In [1]:
using MTH229
using Plots
plotly()

┌ Info: For saving to png with the Plotly backend PlotlyBase has to be installed.
└ @ Plots /Users/verzani/.julia/packages/Plots/1KWPG/src/backends.jl:318


Plots.PlotlyBackend()

Recall, when `MTH229` is loaded, the same prime notation of mathematics is available in `Julia` for indicating derivatives of functions (through `ForwardDiff`).


## Quick background


Read about this material here: [Exploring first and second derivatives with Julia](http://mth229.github.io/first-second-derivatives.html).


For the impatient, this assignment looks at the relationship between a function, $f(x)$, and its first and second derivatives: $f'(x)$ and $f''(x)$. The basic relationship can be summarized (though the devil is in the details) by:


  * If the first derivative is *positive* on $(a,b)$ then the function is *increasing* on $(a,b)$.
  * If the second derivative is *positive* on $(a,b)$ then the function is *concave up* on $(a,b)$.


(The "devil" here is that the converse statements are usually - but not always - true.)


Some key  definitions are:


  * A **critical** point of $f$ is a value in the domain of $f(x)$ for which the derivative is $0$ or undefined. These are often–-but **not always**–-where $f(x)$ has a local maximum or minimum.
  * An **inflection point** of $f$ is a value in the domain of $f(x)$ where the concavity of $f$ *changes*. (These are *often*–-but **not always**–-where $f''(x)=0$.)


These two relationships and definitions are put to use to characterize *local extrema* of a function via one of two "derivative" tests:


  * The **first derivative test**:  This states that  if $c$ is a critical point of $f(x)$ then if $f'(x)$ changes sign from $+$ to $-$ at $c$ then $f(c)$ is a local maximum and if $f'(x)$ changes sign from $-$ to $+$ then $f(c)$ is a local minimum. If there is no sign change, then $f(c)$ is neither a local minimum or maximum.
  * The **second derivative test**: This states that if $c$ is a critical point of $f(x)$ and $f''(c) > 0$ then $f(c)$ is a local minimum and if $f''(c) < 0$ then $f(c)$ is a local maximum. The test says nothing about the case $f''(c) = 0$.


---


We investigate these concepts in `Julia` both graphically and numerically.


For the graphical exploration, the `plotif` function from the `MTH229` package is quite useful. It is used to plot a function `f` using two colors; the color choice depending on whether the second function, `g` is positive or not. (Basically it does `plot(f, a, b); plot!(x -> g(x) > 0.0 ? f(x) : NaN, a, b)`.)


This function can be used to graphically illustrate where the graph of `f` is *positive*, *increasing*, or *concave up*: `plotif(f, f, a, b)` will show a different color when $f(x)$ is *positive*, `plotif(f, f', a, b)` will show a different color when $f(x)$ is *increasing*, and  `plotif(f, f'', a, b)` will show a different color when $f(x)$ is *concave up*. For example, here we see where the following `f` is increasing:


In [2]:
f(x) = 1 + cos(x) + cos(2x)
plotif(f, f', 0, 2pi)  # color increasing
plot!(zero)

A similar helpful function is `sign_chart` which will numerically identify zero crossings and infinities and indicate how the function changes sign:


In [3]:
sign_chart(f, 0, 2pi)

4-element Vector{NamedTuple{(:DNE_0_∞, :sign_change), Tuple{Float64, String}}}:
 (DNE_0_∞ = 1.5707963267948966, sign_change = "+ → -")
 (DNE_0_∞ = 2.0943951023931953, sign_change = "- → +")
 (DNE_0_∞ = 4.1887902047863905, sign_change = "+ → -")
 (DNE_0_∞ = 4.71238898038469, sign_change = "- → +")

---


Once eyes are trained to identify zeros, critical points, or inflection points of a function, we can use numeric methods to zoom in on more accurate values.  Recall, `fzero(f, a, b)` will find a zero of `f` **if** `[a,b]` is a *bracketing* interval (`f` takes different signs at the endpoints); and `fzeros(f, a, b)` will look for all zeros of `f` within the interval `[a,b]`, not necessarily a bracketing one. The `fzeros` function returns a container of values, which may, of course, be empty.


For example to find a zero in `f` near `1.5` we would first graph. We can then identify $[1,2]$ as a bracketing interval, and solve with:


In [4]:
f(x) = 1 + cos(x) + cos(2x)
fzero(f, 1, 2)

1.5707963267948966

If our task was to get *all* critical points of `f` in the interval $(0, 2\pi)$, then `fzeros` is the easier-to-use choice: As `f` is continuously differentiable, all critical points are given by solving $f'(x)=0$:


In [5]:
zs = fzeros(f', 0, 2pi)

5-element Vector{Float64}:
 0.0
 1.8234765819369751
 3.141592653589793
 4.459708725242611
 6.283185307179586

The answer from `fzeros` is a vector of values. You can get individual ones different ways or work with them all at once. For example, here is the function's value at each of the critical points:


In [6]:
f.(zs)   # or more explicitly map(f, zs)

5-element Vector{Float64}:
  3.0
 -0.125
  1.0
 -0.125
  3.0

## Careful


The `fzeros` function is only *pretty* good at finding all the zeros over the interval. For some functions – especially those cooked up by clever math professors – the choice of interval can lead to `fzeros` finding fewer than is mathematically possible. The function should be used in combination with a plot and with as narrow an interval specified, as reasonable.


---
